name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2-beta
        with:
          version: 23.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Install Json server 0.17.4
        run: npm install json-server@0.17.4

      - name: Run json server
        run: npx json-server --watch db.json --port 3000

      - name: Build Application
        run: npx ember build --environment=ci

      - name: Run deploy script
        run: sh ./scripts/deploy-to-gh-pages.sh